// Past project categories with links
const pastProjects = {
    en: [
        {
            category: 'WordPress / WooCommerce',
            color: '#21759b',
            icon: '🌐',
            items: [
                { name: 'Retail Servicios Externos', url: 'https://retailserviciosexternos.com/', note: 'Bridge, Elementor, Custom Field, Membership, Zendesk Chat' },
                { name: 'Wine Tourism', url: 'https://www.winetourism.com/', note: 'Bridge, Elementor, Custom Field, Membership, Zendesk Chat' },
                { name: 'The Prehab Guys', url: 'https://theprehabguys.com', note: 'Bridge, Elementor, Custom Field, Membership, Zendesk Chat' },
                { name: 'Clayton Fit', url: 'https://claytonfit.com/', note: 'Avada, WooCommerce, Klaviyo, Fusion Builder' },
                { name: 'PPSC', url: 'https://getppsc.com/', note: 'My Listing, WooCommerce, Elementor, Yoast SEO, LiveChat' },
                { name: 'Neurocentric Approach', url: 'https://neurocentricapproach.com/', note: '' },
                { name: 'Dr. Justin Dean', url: 'https://drjustindean.com', note: 'Avada, WooCommerce' },
                { name: 'Dr. John Rusin', url: 'https://drjohnrusin.com/', note: 'Avada, WooCommerce' },
                { name: 'Big Ass Fans', url: 'https://www.bigassfans.com/', note: '' },
                { name: 'Element Case', url: 'https://www.elementcase.com/', note: '' },
                { name: 'Federal Resources', url: 'https://www.federalresources.com/', note: '' },
                { name: 'Play at Gila', url: 'https://playatgila.com/', note: '' },
                { name: 'FSL Ltd', url: 'https://www.fsltd.com/', note: '' },
                { name: 'PRM Law', url: 'https://www.prmlaw.ca/', note: '' },
                { name: 'Ridgeview Baptist Church', url: 'http://www.ridgeviewbaptistchurch.com/', note: '' },
                { name: 'Flora Bowley', url: 'https://florabowley.com/', note: '' },
                { name: 'Million Dollar Practice', url: 'https://www.milliondollarpractice.net/', note: '' },
                { name: 'Chocholik', url: 'http://www.chocholik.com/', note: '' },
                { name: 'My Kitchen Heals', url: 'https://www.mykitchenheals.com.au/', note: '' },
                { name: 'Lux Capital', url: 'https://luxcapital.com/', note: '' },
            ],
        },
        {
            category: 'Blockchain / Crypto / NFT',
            color: '#f7931a',
            icon: '⛓️',
            items: [
                { name: 'CroxSwap Farm', url: 'https://crox-frontend-farm-2-0-3lmlt1lf8-croxswapcom.vercel.app/', note: 'Swap, Farming' },
                { name: 'CryptoBlades', url: 'https://www.cryptoblades.io/', note: 'Crypto Game' },
                { name: 'Sloto (Gambling)', url: 'https://sloto.netlify.app/', note: 'Gambling' },
                { name: 'Gamdom', url: 'https://gamdom.com/', note: 'Roller reference' },
                { name: 'Rollette Bet', url: 'https://rollettebet.com/', note: 'Roller reference' },
                { name: 'CSGOEmpire Coinflip', url: 'https://csgoempire.com/coinflip', note: 'Coinflip' },
                { name: 'Magic Eden — DegenFatCats', url: 'https://magiceden.io/marketplace/degenfatcats', note: 'Solana NFT' },
                { name: 'Chumba Casino', url: 'https://www.chumbacasino.com', note: 'Casino' },
                { name: 'NearNauts', url: 'https://nearnauts.io/', note: 'NFT Marketplace' },
                { name: 'Axie Infinity Marketplace', url: 'https://marketplace.axieinfinity.com/axie', note: 'NFT Marketplace' },
                { name: 'Meka Verse', url: 'https://www.themekaverse.com/', note: 'Vue/Nuxt/Node' },
                { name: 'Divine Anarchy', url: 'https://www.divineanarchy.com/', note: 'NFT' },
                { name: 'Doge Pound NFT', url: 'https://thedogepoundnft.com/app', note: 'NFT' },
                { name: 'Baboons', url: 'https://baboons.gg/', note: 'NFT' },
                { name: 'Billionaire Club NFT', url: 'https://billionaireclubnft.com', note: 'NFT' },
                { name: 'Fishbowl Heads', url: 'https://fishbowlheads.com/', note: 'NFT' },
                { name: 'Best NFT Maker', url: 'https://bestnftmaker.com', note: 'NFT' },
                { name: 'Ghost Market', url: 'https://ghostmarket.io', note: 'NFT' },
                { name: 'Battle Hero', url: 'https://battlehero.io/', note: 'NFT' },
                { name: 'Meta Bounty Hunters', url: 'https://metabountyhunters.io', note: 'NFT Mint' },
                { name: 'Galactic Empire', url: 'https://galacticempire.io/', note: 'NFT Mint' },
                { name: 'Psycho Teddy NFT', url: 'https://psychoteddynft.com/', note: 'NFT Mint' },
                { name: 'Hype Hippo', url: 'https://hypehippo.io', note: 'NFT Mint' },
                { name: 'Panda Dynasty', url: 'https://pandadynasty.io/', note: 'NFT Mint' },
                { name: 'Posh Pandas', url: 'https://www.poshpandas.ca/', note: 'NFT Mint' },
                { name: 'Whalies Club', url: 'https://whalies.club/mint', note: 'NFT Mint' },
                { name: 'Kandi Kids', url: 'https://kandikids.io/', note: 'NFT Mint' },
                { name: 'Bella DAO', url: 'https://belladao.io/', note: 'NFT Mint' },
                { name: 'Kozmo Aliens', url: 'https://www.kozmoaliens.com/', note: 'NFT Mint' },
                { name: 'Knights of Chain', url: 'https://knightsofchain.com/', note: 'NFT Mint' },
                { name: 'ZAC Finance', url: 'https://zac.finance/', note: 'DeFi' },
                { name: 'Ebbi Coin ICO', url: 'http://ebbicoin.com/', note: 'ICO' },
                { name: 'Rouge Network', url: 'https://rouge.network/', note: 'ICO' },
                { name: 'Bitrue', url: 'https://www.bitrue.com/', note: 'ICO / Exchange' },
                { name: 'Top 100 Token', url: 'https://top100token.com/', note: 'Token Listing' },
                { name: 'Babylon Swap Game', url: 'https://game.babylonswap.finance/', note: 'Crypto Game' },
                { name: 'Deam Chain', url: 'https://deamchain.com/', note: 'Forking Blockchain' },
                { name: 'Soul Hero NFT Staking', url: 'http://www.soulhero.io/', note: 'NFT Staking' },
                { name: 'Lucky Shiba Presale', url: 'https://luckyshiba.org/', note: 'Presale' },
            ],
        },
        {
            category: 'Next.js',
            color: '#000000',
            icon: '▲',
            items: [
                { name: 'PeopleGoal', url: 'https://www.peoplegoal.com/', note: '' },
                { name: 'Cogofly', url: 'https://www.cogofly.com/en/', note: '' },
                { name: 'Wealthsimple', url: 'https://www.wealthsimple.com/en-gb/', note: '' },
                { name: 'The Custom Movement', url: 'https://www.thecustommovement.com/', note: '' },
                { name: 'Mercari', url: 'https://www.mercari.com/', note: '' },
                { name: 'Culligan', url: 'https://www.culligan.com/', note: '' },
                { name: 'Sentry', url: 'https://sentry.io/', note: '' },
            ],
        },
        {
            category: 'React',
            color: '#61dafb',
            icon: '⚛️',
            items: [
                { name: 'Leasing Options', url: 'https://leasingoptions.co.uk', note: 'React' },
                { name: 'Subol', url: 'https://subol.io/', note: '' },
                { name: 'The Fresh Market', url: 'https://www.thefreshmarket.com/', note: '' },
                { name: 'Angle Platform', url: 'https://angleplatform.com/', note: '' },
                { name: 'Nopeet Store', url: 'https://www.nopeetstore.com/', note: '' },
                { name: 'Dubai Blocks', url: 'https://dubaiblocks.com/', note: 'Shopify' },
                { name: 'Juliana Falldin', url: 'https://www.julianafalldin.com/', note: '' },
                { name: 'Belladonna Gowns', url: 'https://www.belladonnagowns.com.au/', note: '' },
                { name: 'Moon Vision', url: 'https://www.moonvision.io/', note: '' },
                { name: 'Animatly', url: 'https://animatly.io/', note: '' },
                { name: 'Orangetheory', url: 'https://www.orangetheory.com/en-us/', note: 'React.js, Laravel, MySQL' },
                { name: 'Tree DeFi', url: 'https://treedefi.com/', note: 'React + NFT' },
                { name: 'Hanai World', url: 'https://hanaiworld.com/', note: 'React + NFT' },
                { name: 'NFTrade', url: 'https://nftrade.com/', note: 'React + NFT' },
                { name: 'Opacity', url: 'https://www.opacity.io/', note: 'React + Crypto' },
                { name: 'Mill3 Studio', url: 'https://mill3.studio/en/', note: '' },
            ],
        },
        {
            category: 'Vue.js / Nuxt.js',
            color: '#42b883',
            icon: '💚',
            items: [
                { name: 'Tweezer World', url: 'https://tweezerworld.com/', note: 'WordPress' },
                { name: 'Rudolfson', url: 'https://www.rudolfson.com/', note: 'Vue.js, Nuxt.js, Node.js' },
                { name: 'Airfare Pouch', url: 'https://airfarepouch.com/', note: '' },
                { name: 'ZMot Institute', url: 'https://zmotinstitute.com/', note: 'Nuxt' },
                { name: 'Family Tree 365', url: 'https://www.familytree365.com/', note: 'Nuxt' },
                { name: 'Seekadoo', url: 'https://seekadoo.com/', note: 'Nuxt' },
                { name: 'UXPressia', url: 'https://uxpressia.com/', note: 'Nuxt' },
            ],
        },
        {
            category: 'Laravel / PHP',
            color: '#ff2d20',
            icon: '🔴',
            items: [
                { name: 'The Hamptons Apartments', url: 'https://thehamptonsapartments.com.au', note: '' },
                { name: 'Manhattan Apartments', url: 'https://www.manhattanapartments.com.au/', note: '' },
                { name: 'Legacy A Brand', url: 'https://legacyabrand.com/', note: '' },
                { name: 'Global Shares Group', url: 'https://globalsharesgroup.com/', note: '' },
                { name: 'Resell Content', url: 'https://resellcontent.com/', note: '' },
                { name: 'Aussie Medicos', url: 'https://aussiemedicos.com.au/', note: '' },
                { name: 'Tech Fix AE', url: 'https://www.techfix.ae/', note: '' },
                { name: 'Baby Buy', url: 'https://babybuy.am/', note: '' },
                { name: 'GoPromenad', url: 'https://gopromenad.com/', note: 'React + Vue + Laravel + socket.io' },
            ],
        },
        {
            category: 'Shopify',
            color: '#96bf48',
            icon: '🛍️',
            items: [
                { name: 'Scarlett Wear', url: 'https://scarlettwear.com/', note: '' },
                { name: 'Koraloc', url: 'https://koraloc.com/', note: '' },
                { name: 'Ochocos', url: 'https://ochocos.com/', note: '' },
                { name: 'Jamemme', url: 'https://jamemme.com/', note: '' },
                { name: 'Drink Dezo', url: 'https://www.drinkdezo.com/', note: '' },
                { name: 'Sweet Kick', url: 'https://sweetkick.com/', note: '' },
                { name: 'Level Foods', url: 'https://levelfoods.com/', note: '' },
                { name: 'Peppi Gel', url: 'https://www.peppigel.com/', note: '' },
                { name: 'Holy Stone Store', url: 'https://store.holystone.com/', note: '' },
                { name: 'Seven and Sun', url: 'https://sevenandsun.com/', note: '' },
                { name: 'Brinker & Eliza', url: 'https://brinkerandeliza.com/', note: '' },
                { name: 'Electric Picks', url: 'https://electricpicks.com/', note: '' },
            ],
        },
        {
            category: 'Magento / OpenCart / Angular',
            color: '#ee0000',
            icon: '🔧',
            items: [
                { name: 'Muzzle Loaders', url: 'https://www.muzzle-loaders.com', note: 'Magento' },
                { name: 'Montana Woodworks', url: 'https://montanawoodworks.com/', note: 'Magento' },
                { name: 'Every Man Jack', url: 'https://www.everymanjack.com/', note: 'Magento' },
                { name: 'Beauty Mall', url: 'https://www.beautymall.ca/', note: 'OpenCart' },
                { name: 'Rentberry', url: 'https://rentberry.com/', note: 'Angular 11' },
                { name: 'JD Landscaping', url: 'https://jdlandscaping.net/', note: 'Angular 11' },
                { name: 'Venus Remedies', url: 'https://venusremedies.com/', note: 'Angular' },
            ],
        },
    ],
    ja: [
        {
            category: 'WordPress / WooCommerce',
            color: '#21759b',
            icon: '🌐',
            items: [
                { name: 'Retail Servicios Externos', url: 'https://retailserviciosexternos.com/', note: 'Bridge、Elementor、カスタムフィールド、会員機能、Zendesk Chat' },
                { name: 'Wine Tourism', url: 'https://www.winetourism.com/', note: 'Bridge、Elementor、カスタムフィールド、会員機能、Zendesk Chat' },
                { name: 'The Prehab Guys', url: 'https://theprehabguys.com', note: 'Bridge、Elementor、カスタムフィールド、会員機能、Zendesk Chat' },
                { name: 'Clayton Fit', url: 'https://claytonfit.com/', note: 'Avada、WooCommerce、Klaviyo、Fusion Builder' },
                { name: 'PPSC', url: 'https://getppsc.com/', note: 'My Listing、WooCommerce、Elementor、Yoast SEO、LiveChat' },
                { name: 'Neurocentric Approach', url: 'https://neurocentricapproach.com/', note: '' },
                { name: 'Dr. Justin Dean', url: 'https://drjustindean.com', note: 'Avada、WooCommerce' },
                { name: 'Dr. John Rusin', url: 'https://drjohnrusin.com/', note: 'Avada、WooCommerce' },
                { name: 'Big Ass Fans', url: 'https://www.bigassfans.com/', note: '' },
                { name: 'Element Case', url: 'https://www.elementcase.com/', note: '' },
                { name: 'Federal Resources', url: 'https://www.federalresources.com/', note: '' },
                { name: 'Play at Gila', url: 'https://playatgila.com/', note: '' },
                { name: 'FSL Ltd', url: 'https://www.fsltd.com/', note: '' },
                { name: 'PRM Law', url: 'https://www.prmlaw.ca/', note: '' },
                { name: 'Flora Bowley', url: 'https://florabowley.com/', note: '' },
                { name: 'Million Dollar Practice', url: 'https://www.milliondollarpractice.net/', note: '' },
                { name: 'Lux Capital', url: 'https://luxcapital.com/', note: '' },
            ],
        },
        {
            category: 'ブロックチェーン / 暗号資産 / NFT',
            color: '#f7931a',
            icon: '⛓️',
            items: [
                { name: 'CroxSwap Farm', url: 'https://crox-frontend-farm-2-0-3lmlt1lf8-croxswapcom.vercel.app/', note: 'スワップ・ファーミング' },
                { name: 'CryptoBlades', url: 'https://www.cryptoblades.io/', note: '暗号資産ゲーム' },
                { name: 'Sloto（ギャンブル）', url: 'https://sloto.netlify.app/', note: 'ギャンブル' },
                { name: 'Gamdom', url: 'https://gamdom.com/', note: 'ローラー参考' },
                { name: 'CSGOEmpire Coinflip', url: 'https://csgoempire.com/coinflip', note: 'コインフリップ' },
                { name: 'Magic Eden — DegenFatCats', url: 'https://magiceden.io/marketplace/degenfatcats', note: 'Solana NFT' },
                { name: 'Chumba Casino', url: 'https://www.chumbacasino.com', note: 'カジノ' },
                { name: 'NearNauts', url: 'https://nearnauts.io/', note: 'NFTマーケットプレイス' },
                { name: 'Axie Infinity Marketplace', url: 'https://marketplace.axieinfinity.com/axie', note: 'NFTマーケットプレイス' },
                { name: 'Meka Verse', url: 'https://www.themekaverse.com/', note: 'Vue/Nuxt/Node' },
                { name: 'Divine Anarchy', url: 'https://www.divineanarchy.com/', note: 'NFT' },
                { name: 'Baboons', url: 'https://baboons.gg/', note: 'NFT' },
                { name: 'Battle Hero', url: 'https://battlehero.io/', note: 'NFT' },
                { name: 'Meta Bounty Hunters', url: 'https://metabountyhunters.io', note: 'NFTミント' },
                { name: 'Galactic Empire', url: 'https://galacticempire.io/', note: 'NFTミント' },
                { name: 'Panda Dynasty', url: 'https://pandadynasty.io/', note: 'NFTミント' },
                { name: 'Whalies Club', url: 'https://whalies.club/mint', note: 'NFTミント' },
                { name: 'Kandi Kids', url: 'https://kandikids.io/', note: 'NFTミント' },
                { name: 'ZAC Finance', url: 'https://zac.finance/', note: 'DeFi' },
                { name: 'Ebbi Coin ICO', url: 'http://ebbicoin.com/', note: 'ICO' },
                { name: 'Bitrue', url: 'https://www.bitrue.com/', note: 'ICO / 取引所' },
                { name: 'Top 100 Token', url: 'https://top100token.com/', note: 'トークン上場' },
                { name: 'Babylon Swap Game', url: 'https://game.babylonswap.finance/', note: '暗号資産ゲーム' },
                { name: 'Deam Chain', url: 'https://deamchain.com/', note: 'ブロックチェーンフォーク' },
                { name: 'Soul Hero NFT Staking', url: 'http://www.soulhero.io/', note: 'NFTステーキング' },
                { name: 'Lucky Shiba Presale', url: 'https://luckyshiba.org/', note: 'プレセール' },
            ],
        },
        {
            category: 'Next.js',
            color: '#000000',
            icon: '▲',
            items: [
                { name: 'PeopleGoal', url: 'https://www.peoplegoal.com/', note: '' },
                { name: 'Cogofly', url: 'https://www.cogofly.com/en/', note: '' },
                { name: 'Wealthsimple', url: 'https://www.wealthsimple.com/en-gb/', note: '' },
                { name: 'The Custom Movement', url: 'https://www.thecustommovement.com/', note: '' },
                { name: 'Mercari', url: 'https://www.mercari.com/', note: '' },
                { name: 'Culligan', url: 'https://www.culligan.com/', note: '' },
                { name: 'Sentry', url: 'https://sentry.io/', note: '' },
            ],
        },
        {
            category: 'React',
            color: '#61dafb',
            icon: '⚛️',
            items: [
                { name: 'Leasing Options', url: 'https://leasingoptions.co.uk', note: 'React' },
                { name: 'The Fresh Market', url: 'https://www.thefreshmarket.com/', note: '' },
                { name: 'Orangetheory', url: 'https://www.orangetheory.com/en-us/', note: 'React.js、Laravel、MySQL' },
                { name: 'Tree DeFi', url: 'https://treedefi.com/', note: 'React + NFT' },
                { name: 'Hanai World', url: 'https://hanaiworld.com/', note: 'React + NFT' },
                { name: 'NFTrade', url: 'https://nftrade.com/', note: 'React + NFT' },
                { name: 'Opacity', url: 'https://www.opacity.io/', note: 'React + 暗号資産' },
                { name: 'Mill3 Studio', url: 'https://mill3.studio/en/', note: '' },
                { name: 'Animatly', url: 'https://animatly.io/', note: '' },
            ],
        },
        {
            category: 'Vue.js / Nuxt.js',
            color: '#42b883',
            icon: '💚',
            items: [
                { name: 'Rudolfson', url: 'https://www.rudolfson.com/', note: 'Vue.js、Nuxt.js、Node.js' },
                { name: 'Airfare Pouch', url: 'https://airfarepouch.com/', note: '' },
                { name: 'ZMot Institute', url: 'https://zmotinstitute.com/', note: 'Nuxt' },
                { name: 'Family Tree 365', url: 'https://www.familytree365.com/', note: 'Nuxt' },
                { name: 'Seekadoo', url: 'https://seekadoo.com/', note: 'Nuxt' },
                { name: 'UXPressia', url: 'https://uxpressia.com/', note: 'Nuxt' },
            ],
        },
        {
            category: 'Laravel / PHP',
            color: '#ff2d20',
            icon: '🔴',
            items: [
                { name: 'The Hamptons Apartments', url: 'https://thehamptonsapartments.com.au', note: '' },
                { name: 'Manhattan Apartments', url: 'https://www.manhattanapartments.com.au/', note: '' },
                { name: 'Legacy A Brand', url: 'https://legacyabrand.com/', note: '' },
                { name: 'Resell Content', url: 'https://resellcontent.com/', note: '' },
                { name: 'Aussie Medicos', url: 'https://aussiemedicos.com.au/', note: '' },
                { name: 'Tech Fix AE', url: 'https://www.techfix.ae/', note: '' },
                { name: 'Baby Buy', url: 'https://babybuy.am/', note: '' },
                { name: 'GoPromenad', url: 'https://gopromenad.com/', note: 'React + Vue + Laravel + socket.io' },
            ],
        },
        {
            category: 'Shopify',
            color: '#96bf48',
            icon: '🛍️',
            items: [
                { name: 'Scarlett Wear', url: 'https://scarlettwear.com/', note: '' },
                { name: 'Koraloc', url: 'https://koraloc.com/', note: '' },
                { name: 'Drink Dezo', url: 'https://www.drinkdezo.com/', note: '' },
                { name: 'Sweet Kick', url: 'https://sweetkick.com/', note: '' },
                { name: 'Level Foods', url: 'https://levelfoods.com/', note: '' },
                { name: 'Holy Stone Store', url: 'https://store.holystone.com/', note: '' },
                { name: 'Electric Picks', url: 'https://electricpicks.com/', note: '' },
            ],
        },
        {
            category: 'Magento / OpenCart / Angular',
            color: '#ee0000',
            icon: '🔧',
            items: [
                { name: 'Muzzle Loaders', url: 'https://www.muzzle-loaders.com', note: 'Magento' },
                { name: 'Montana Woodworks', url: 'https://montanawoodworks.com/', note: 'Magento' },
                { name: 'Every Man Jack', url: 'https://www.everymanjack.com/', note: 'Magento' },
                { name: 'Beauty Mall', url: 'https://www.beautymall.ca/', note: 'OpenCart' },
                { name: 'Rentberry', url: 'https://rentberry.com/', note: 'Angular 11' },
                { name: 'JD Landscaping', url: 'https://jdlandscaping.net/', note: 'Angular 11' },
                { name: 'Venus Remedies', url: 'https://venusremedies.com/', note: 'Angular' },
            ],
        },
    ],
}

export { pastProjects }
